"""create class tables for itinerary data

Revision ID: fb2150fbbbea
Revises: 24420a3c270a
Create Date: 2026-09-17 18:13:31.420775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2150fbbbea'
down_revision = '24420a3c270a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('destination_type', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destinations_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_destinations_slug'), ['slug'], unique=True)

    op.create_table('transports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport_type', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accommodations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accommodation_type', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodations_destination_id'), ['destination_id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_destination_id'), ['destination_id'], unique=False)

    op.create_table('destination_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destination_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destination_images_destination_id'), ['destination_id'], unique=False)

    op.create_table('accommodation_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accommodation_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodation_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_images_accommodation_id'), ['accommodation_id'], unique=False)

    op.create_table('accommodation_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accommodation_id', sa.UUID(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('meal_plan', sa.String(length=100), nullable=True),
    sa.Column('price_per_night', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodation_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_rates_accommodation_id'), ['accommodation_id'], unique=False)

    op.create_table('activity_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_images_activity_id'), ['activity_id'], unique=False)

    op.create_table('activity_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pricing_type', sa.String(length=50), nullable=False),
    sa.Column('min_people', sa.Integer(), nullable=True),
    sa.Column('max_people', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_rates_activity_id'), ['activity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_rates_activity_id'))

    op.drop_table('activity_rates')
    with op.batch_alter_table('activity_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_images_activity_id'))

    op.drop_table('activity_images')
    with op.batch_alter_table('accommodation_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_rates_accommodation_id'))

    op.drop_table('accommodation_rates')
    with op.batch_alter_table('accommodation_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_images_accommodation_id'))

    op.drop_table('accommodation_images')
    with op.batch_alter_table('destination_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destination_images_destination_id'))

    op.drop_table('destination_images')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_destination_id'))

    op.drop_table('activities')
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodations_destination_id'))

    op.drop_table('accommodations')
    op.drop_table('transports')
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinations_slug'))
        batch_op.drop_index(batch_op.f('ix_destinations_name'))

    op.drop_table('destinations')
    # ### end Alembic commands ###
